#!/bin/bash
#
# Configuration related to the user
#

GITLAB_PRIVATE_TOKEN=__YOUR_GITLAB_TOKEN_HERE__

# Optionnal

# Require to clone using http/https
#GITLAB_USER=__YOUR_GIT_USER__
#GITLAB_PASSWORD=$(url_encode '__YOUR_GIT_USER_PASSWORD__')
#GITLAB_CLONE_HTTP_PREFIX="https://${GITLAB_USER}:${GITLAB_PASSWORD}@${GITLAB_URL_PREFIX#"https://"}"

# If client certificate is needed for HTTPS communication with GitLab server
#GITLAB_CLIENT_CERTIFICATE=__PATH_TO_YOUR_CLIENT_CERTIFICATE__
#GITLAB_CLIENT_CERTIFICATE_PASSWORD=__PASSWORD_FOR_YOUR_CLIENT_CERTIFICATE__
#GITLAB_PRIVATE_KEY=__PATH_TO_YOUR_PRIVATE_KEY__
