#!/bin/bash
#
# Default values for users
#
GITLAB_USER_INITIAL_PASSWORD="P@zzW0rd!_CHANGE_ME"

GITLAB_USER_CAN_CREATE_GROUP=false
GITLAB_USER_CONFIRM=true
GITLAB_USER_IS_ADMIN=false
GITLAB_USER_PROJECTS_LIMIT=10
GITLAB_USER_RESET_PASSWORD=true
GITLAB_USER_SHARED_RUNNERS_MINUTES_LIMIT=0
