#!/bin/bash
#
# Default values for projects
#
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_DESCRIPTION='PLEASE update description'

# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_CONTAINER_REGISTRY_ENABLED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_ISSUES_ENABLED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_JOBS_ENABLED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_LFS_ENABLED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_MERGE_REQUESTS_ENABLED=true
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_ONLY_ALLOW_MERGE_IF_ALL_DISCUSSIONS_ARE_RESOLVED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_ONLY_ALLOW_MERGE_IF_PIPELINE_SUCCEEDS=true
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_PRINTING_MERGE_REQUEST_LINK_ENABLED=true
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_PUBLIC_JOBS=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_REQUEST_ACCESS_ENABLED=true
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_SNIPPETS_ENABLED=false
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_VISIBILITY=internal
# shellcheck disable=SC2034
GITLAB_DEFAULT_PROJECT_WIKI_ENABLED=false
