#!/bin/bash
#
# Default values for groups
#
GITLAB_GROUP_DESCRIPTION="PLEASE update description"

GITLAB_GROUP_LFS_ENABLED=false
GITLAB_GROUP_MEMBERSHIP_LOCK=true
GITLAB_GROUP_REQUEST_ACCESS_ENABLED=true
GITLAB_GROUP_SHARE_WITH_GROUP_LOCK=true
GITLAB_GROUP_VISIBILITY=internal
