#!/bin/bash
#
# Default values for users
#
USER_RESET_PASSWORD=true
USER_PROJECTS_LIMIT=10
USER_IS_ADMIN=false
USER_CAN_CREATE_GROUP=false
USER_CONFIRM=true
USER_SHARED_RUNNERS_MINUTES_LIMIT=0
USER_INITIAL_PASSWORD="P@zzW0rd!"
