#!/bin/bash
#
# Default values for projects
#
PROJECT_ISSUES_ENABLED=false
PROJECT_JOBS_ENABLED=false
PROJECT_LFS_ENABLED=false
PROJECT_MERGE_REQUESTS_ENABLED=true
PROJECT_PRINTING_MERGE_REQUEST_LINK_ENABLED=true
PROJECT_REQUEST_ACCESS_ENABLED=true
PROJECT_SNIPPETS_ENABLED=false
PROJECT_VISIBILITY=internal
PROJECT_WIKI_ENABLED=false
PROJECT_DESCRIPTION="PLEASE update description"
